test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage/%{tenant}") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage", "tenants", Rails.env, "%{tenant}", "files") %>

<% purestorage_env_name = Rails.env.beta? ? "staging" : Rails.env %>
purestorage:
  service: S3
  bucket: fizzy-<%= purestorage_env_name %>-activestorage
  endpoint: "https://storage.basecamp.com"
  ssl_verify_peer: false # FIXME: using self-signed cert internally
  force_path_style: true
  request_checksum_calculation: when_required # default is when_supported with CRC64NVME checksum which FlashBlade doesn't support
  response_checksum_validation: when_required # default is when_supported with CRC64NVME checksum which FlashBlade doesn't support
  region: us-east-1 # default region required for signer
  access_key_id: <%= Rails.application.credentials.dig(:active_storage, :purestorage_service, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:active_storage, :purestorage_service, :secret_access_key) %>

mirror:
  service: Mirror
  primary: local
  mirrors: [ purestorage ]
